baseURL = "https://desarrollo-paquetes-avanzado-2025.netlify.app/"
languageCode = "es"
defaultContentLanguage = "es"
title = "Desarrollo de Paquetes Avanzado"
enableEmoji = true
pygmentsUseClasses=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"
    
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.es]
title = "Desarrollo de Paquetes Avanzado"
weight = 1
languageName = "Español"

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repositorio en GitHub"
identifier = "ds"
url = "https://github.com/ropensci-training/2025-pkg-dev-rocket"
weight = 10


[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Gracias"
url = "/credits"
weight = 30

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[params]
  editURL = "https://github.com/ropensci-training/2024-pkg-dev-rocket/edit/main/content/"
  description = "Desarrollo de paquetes Avanzados: no es ciencia espacial"
  author = "Maëlle Salmon"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params.reveal_hugo]
theme = "white"
load_default_plugins = false
plugins = [
  "reveal-js/plugin/zoom-js/zoom.js",
  "reveal-js/plugin/notes/notes.js",
]
